name: Roots and Wings
favicon: null
layout_spectrum: 0.75667
typography_spectrum: 0.21165
title: Roots and Wings
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#110f17'
    - '#d7d6d2'
    - '#bab8b9'
    - '#655057'
    - '#44343f'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
