name: Roots and Wings
favicon: null
layout_spectrum: 0.1717703603208065
typography_spectrum: 0.8346021347679198
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5973309818655252
  lightness: 0.07123585138469934
  saturation: 0.7163005801849067
  rhythmicContrast: 0.8479617410339415
purpose: []
